project:
  type: website

website:
  title: "PandasLab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: python.qmd
        text: Python
      - href: pandas.qmd
        text: Pandas
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



