project:
  type: website

execute:
  debug: true

  
website:
  title: "PandasLab"
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "HOME"
        contents: 
          - index.qmd

      - section: "PYTHON"
        contents:
          - python.qmd
          - py-syntaxe.qmd
      - section: "PANDAS"
        contents:
          - pandas.qmd
          - exercice-pan.qmd
      - section: "DATA VIZ"
        contents:
           - visualisation.qmd
           - exercice-viz.qmd
      
      - section: "A PROPOS"
        contents: 
            - about.qmd
theme:
  light: flatly
  dark: darkly

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




