project:
  type: website

website:
  title: "PandasLab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: python.qmd
        text: Python
      - href: pandas.qmd
        text: Pandas
      - href: about.qmd
        text: About
    cookie-consent:
      type: express
      style: headline
      palette: dark
    theme:
      light: flatly
      dark: darkly


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



