project:
  type: website

website:
  title: "PandasLab"
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "HOME"
        contents: 
          - index.qmd

      - section: "PYTHON"
        contents:
          - python.qmd
          - py-syntaxe.qmd
          # - conditions.qmd
          # - fonctions.qmd
          # - listes.qmd
      - section: "PANDAS"
        contents:
          - pandas.qmd
          - exercice-pan.qmd
      - section: "DATA VIZ"
        contents:
           - visualisation.qmd
           - exercice-viz.qmd
      
      - section: "A PROPOS"
        contents: 
            - about.qmd


    cookie-consent:
      type: express
      style: headline
      palette: dark
theme:
  light: flatly
  dark: darkly


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




