project:
  type: website

website:
  title: "PandasLab"
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "index.qmd"

      - section: "PYTHON"
        contents:
          - python.qmd
          - py-syntaxe.qmd
          - condition.qmd
          - fonctions.qmd
          - listes.qmd
      - section: "PANDAS"
        contents:
          - pandas.qmd
          - layout-knitr.qmd
          - exercice-pan.qmd
      - section: "DATA VIZ"
        contents:
          - visualisation.qmd
          - layout-knitr.qmd
          - exercice-viz.qmd

      - section: "about.qmd"

    cookie-consent:
      type: express
      style: headline
      palette: dark
theme:
  light: flatly
  dark: darkly


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




