---
title: "Cours"
---

### 5.2 Pandas
Le module `pandas` est une bibliothèque de programmation Python extrêmement populaire, utilisée principalement pour l'analyse de données. Elle fournit des structures de données puissantes et flexibles conçues pour travailler facilement avec des données structurées (comme les tableaux et les séries temporelles) de manière intuitive et efficace. Voici quelques aspects clés de `pandas` :

1. **Structures de données principales** : 
   - **DataFrame** : une structure de données tabulaire avec des lignes et des colonnes étiquetées. C'est similaire à une feuille de calcul Excel ou à une table SQL.
   - **Series** : une colonne dans un DataFrame. C'est similaire à une liste en Python, mais avec des fonctionnalités supplémentaires offertes par `pandas`.

2. **Manipulation de données** : 
   - Vous pouvez effectuer des opérations courantes de manipulation de données telles que le tri, le filtrage, la fusion, la jointure et la concaténation.
   - `pandas` est excellent pour gérer des données manquantes, remplacer des valeurs, grouper des données, etc.

3. **Analyse de données** :
   - Il offre des outils pour l'exploration de données, comme le calcul de statistiques et la visualisation.
   - Vous pouvez facilement agir sur chaque colonne d'un DataFrame, par exemple pour appliquer des fonctions mathématiques ou de résumé statistique.

4. **Interfaçage avec d'autres formats de données** :
   - `pandas` peut lire et écrire dans différents formats de fichiers comme CSV, Excel, JSON, HTML, SQL, etc.

5. **Avantages en termes de performance** :
   - Bien que Python soit un langage interprété, `pandas` est construit sur des bibliothèques comme NumPy, ce qui lui permet d'être rapide et efficace.

6. **Utilisation dans divers domaines** :
   - Il est largement utilisé dans la finance, l'économie, la statistique, l'analyse de données, la science des données, et plus encore.

Pour commencer avec `pandas`, vous devez d'abord l'installer (si ce n'est pas déjà fait) en utilisant pip :

```python
pip install pandas
```

Et ensuite, vous pouvez l'importer dans votre script Python :

```python
import pandas as pd
```

`pd` est un alias standard pour `pandas`, utilisé pour simplifier la référence à la bibliothèque dans le code.

<br>
<a href=exercice-pan.qmd class="bouton">📊Commençons les exercices</a>
